language: python
matrix:
  include:
    - name: "Linux Benchmarks"
      python: 3.7
      dist: xenial
      install:
        - pip install --upgrade numpy
        - make build-dependencies
        - make install-executable
      script:
        - make benchmark
    - name: "macOS Benchmarks"
      python: 3.7
      os: osx
      language: generic
      osx_image: xcode12
      install:
        - pip install --upgrade numpy
        - make build-dependencies
        - make install-executable
      script:
        - make benchmark

# The following prevents Travis from running CI on pull requests that come from a
# branch in the same repository. Without this, it will run the same CI for the
# pull request branch _and_ the pull request itself, which makes no sense.
branches:
  only:
    - master
    # We want to build wip/* branches since these are not usually used for PRs
    - /^wip\/.*$/
    # We want to build version tags as well.
    - /^v\d+\.\d+.*$/

notifications:
  email: false
